version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 443:8080
    volumes:
      - /:/data
      - /home/alcestide/.config/filebrowser:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
