version: '3.5'
services:
  headscale:
    container_name: headscale
    volumes:
        - ./config:/etc/headscale/
        - ./data/keys:/var/lib/headscale/
    ports:
        - 27896:8080
    image: headscale/headscale:latest
    command: headscale serve
    restart: unless-stopped

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    pull_policy: always
    container_name: headscale-ui
    restart: unless-stopped
    ports:
        - 9999:80
