version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_CONFIGFILE: /data/navidrome.toml
    volumes:
      - "/home/alcestide/navidrome/data:/data"
      - "/mnt/disk1/Music:/music:ro"
