live_config_reload = true

[colors.bright]
black = "#3d414f"
blue = "#86aaec"
cyan = "#93cee9"
green = "#922cea"
magenta = "#c296eb"
red = "#dd6777"
white = "#cbced3"
yellow = "#ecd3a0"

[colors.cursor]
cursor = "#a5b6cf"
text = "#0d0f18"

[colors.normal]
black = "#1f1f1f"
blue = "#86aaec"
cyan = "#93cee9"
green = "#90ceaa"
magenta = "#c296eb"
red = "#dd6777"
white = "#cbced3"
yellow = "#ecd3a0"

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 11.5

[font.bold]
family = "Fira Code"

[font.bold_italic]
family = "Fira Code"

[font.italic]
family = "Fira Code"

[font.normal]
family = "Fira Code"

[selection]
save_to_clipboard = true

[scrolling]
#decorations = "none"

#dynamic_title = true
#history = 10000
#multiplier = 3
#opacity = 1.0

[window.padding]
x = 15
y = 15

[env]
TERM = "xterm-256color"
